### ISSUE TITLE
[bug] theme can't resolve fonts

### ISSUE THREAD

**Issue by TFK70** [atls/uikit#237]
### Описание бага

1. **@atlantis-lab/theme@latest**
2. Пакет неверно резолвит путь до шрифтов
3. Есть ошибка в globals.ts

### Воспроизведение

Шаги для воспроизведения бага:

1. Инициализируем тему с помощью текущего пакета
2. Кладем туда шрифты
3. Видим ошибку, шрифты не подгружаются
4. При попытке использования injectGlobalStyles нас просят предоставить все 3 аргумента

### Ожидаемое поведение

Путь до шрифтов должен резолвиться корректно

injectGlobalStyles должен запрашивать один обязательный аргумент - fontFaces. Остальные два - опциональные (у них есть initial value)

### Материалы

```javascript
Error: Cannot find module '../fonts/Courier-bold.woff' from 'utils.js'
        at Resolver.resolveModule (/media/darius/6E4CBE7A4CBE3D21/atlantis/atlantis/ui/uikit/node_modules/jest-resolve/build/index.js:259:17)
        at Resolver._getVirtualMockPath (/media/darius/6E4CBE7A4CBE3D21/atlantis/atlantis/ui/uikit/node_modules/jest-resolve/build/index.js:390:14)
        at Resolver._getAbsolutePath (/media/darius/6E4CBE7A4CBE3D21/atlantis/atlantis/ui/uikit/node_modules/jest-resolve/build/index.js:376:14)
        at Resolver.getModuleID (/media/darius/6E4CBE7A4CBE3D21/atlantis/atlantis/ui/uikit/node_modules/jest-resolve/build/index.js:348:31)
        at Runtime._shouldMock (/media/darius/6E4CBE7A4CBE3D21/atlantis/atlantis/ui/uikit/node_modules/jest-runtime/build/index.js:942:37)
        at Runtime.requireModuleOrMock (/media/darius/6E4CBE7A4CBE3D21/atlantis/atlantis/ui/uikit/node_modules/jest-runtime/build/index.js:595:16)
        at fontFace (/media/darius/6E4CBE7A4CBE3D21/atlantis/atlantis/ui/uikit/packages/theme/node_modules/@atlantis-lab/theme/dist/utils.js:11:18)
        at /media/darius/6E4CBE7A4CBE3D21/atlantis/atlantis/ui/uikit/packages/theme/node_modules/@atlantis-lab/theme/dist/utils.js:17:32
        at Array.forEach (<anonymous>)
        at Object.<anonymous>.exports.injectFontFaces (/media/darius/6E4CBE7A4CBE3D21/atlantis/atlantis/ui/uikit/packages/theme/node_modules/@atlantis-lab/theme/dist/utils.js:15:57) {
      code: 'MODULE_NOT_FOUND'
    }

```

### Данные окружения

- Ubuntu@20.04

**Comment by TFK70** [comment]
@TorinAsakura проблема
Суть в том, что тот метод резолва путей до шрифтов который используется сейчас ориентирован на то, что место, где используется `injectGlobalStyles` - конечное, и стили инжектятся прямо там. Но это не так, ведь на проектах мы после инициализации темы еще устанавливаем ее как отдельную зависимость, а стили инжектятся в например `app`, но никак не в самом пакете темы. Это значит, что тема будет искать шрифты отталкиваясь от папки, где был вызван `injectGlobalStyles`, а не там, где находится сама тема

**Подробнее:**
Есть проект. В нем есть пакет `@ui/theme`. Мы инициализируем тему, используя текущий API `injectGlobalStyles`, указывая релятивные пути до шрифтов. Если посмотреть лог прямо там, внутри темы, мы увидим что все корректно.

Теперь, вне ui создаем страницу. На этой странице, непосредственно, нам необходимо заинжектить глобальные стили. Мы устанавливаем `@ui/theme` как зависимость, и он ищет шрифты прямо там, в папке, где находится страница.

В итоге задача такая:

Сделать так, чтобы `@atlantis-lab/theme` резолвил пути до шрифтов за ее пределами (в условном `@ui/theme`)
И сделать так, чтобы этот условный `@ui/theme` резолвил пути до шрифтов уже внутри себя, прямо в нод модулях когда он устанавливается как зависимость

**Comment by TorinAsakura** [comment]
@TFK70 не используй формулировки в духе "сделать так", учись формулировать

**Comment by TorinAsakura** [comment]
@TFK70 и да, я тебе уже про это говорил, когда речь заходила  о шрифтах

**Comment by TFK70** [comment]
@TorinAsakura ну вообще [прекрасно](https://github.com/webpack/webpack/issues/1599#issuecomment-186841345) 
Еще поищу как это можно без шаманств с вебпаком реализовать, если можно. Мне такое решение вообще не нравится, что-то крутить в вебпаке чтобы использовать шаблон темы - слишком сильная головная боль, очевидно
